package com.youmeek.ssm.module.user.mapper;

import com.youmeek.ssm.module.user.pojo.TbUser;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface TbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    int insert(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    int insertSelective(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    TbUser selectByPrimaryKey(Long userId);

    List<TbUser> selectByCondition(TbUser tbUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbUser record);

    @Update("update tb_user set user_img = #{1} where user_name = #{0}")
    int updateImgByName(String userName,String userImg);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbUser record);

    @Select("select * from tb_user limit #{0},#{1} ")
    List<TbUser> selectByPageCondition(int startPage, int pageSize);

    @Select("select count(*) from tb_user where user_name = #{0}")
    int selectTotalPageByUserName(String userName);

    @Select("select count(*) from tb_user")
    int selectTotalPage();
}